<div style="width:400px; padding-top:30px; padding-right:15px; color:#060;">
 <p dir="rtl" style="text-justify:auto;">یکی از دشوار ترین کارهای پرسنل فنی یک سرویس  دهنده اینترنت, تهیه و تنظیم مستندات شبکه و بروز رسانی آن است. از آنجا که در یک  سرویس دهنده اینترنت تعداد زیادی از تجهیزات نصب شده اند و هر کدام از آنها دارای  یک نام کاربری و رمز عبور منحصر به فرد است, به یاد سپردن این همه اطلاعات امری دشوار  و امکان ناپذیر است. زیرا حتی با وجود <span dir="ltr">Radius </span><span dir="rtl"></span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> میبایست یک نام کاربری برای مواقع اضطراری روی سخت افزار وجود داشته باشد. از طرف  دیگر ممکن است به یک سخت افزار افراد متعددی دسترسی داشته باشند که هماهنگی آنها  امری دشوار است.<br />
  یکی دیگر از چالشهای یک  مدیر شبکه, نگهداری و کنترل <span dir="ltr">IP</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> های یک سرویس دهنده اینترنت است. زیرا علاوه بر محاسبه آدرس های خالی برای اختصاص به  مشترکین نیازمند نگهداری مستنداتی دقیق از تاریخ واگذاری و فرد مسوول استفاده  کننده از <span dir="ltr">IP</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> برای ارائه به مراجع ذیصلاح است.<br />
  بروز رسانی و نگهداری  دیتا بیس <span dir="ltr">RIPE NCC</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> نیز امریست دشوار و زمانبر که عدم بروز رسانی دقیق مشکلاتی در درخواست های آتی آن  شرکت از <span dir="ltr">RIPE NCC</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> بوجود می آورد.<br />
  تیم کارانشان نیز با  تجربه زیاد در زمینه سرویس دهی اینترنت و درک خوب از مشکلات مذکور و با هدف ایجاد یک  پرتال قوی برای کمک به مدیران شبکه, اقدام به نوشتن مدیریت اسناد لیمو نموده است.  این پروژه با زبان قدرتمند <span dir="ltr">PHP</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> در  سمت سرور و <span dir="ltr">JavaScript</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> در  سمت کلاینت است. <strong>مدیریت اسناد لیمو  v3.1.1</strong> رایگان بوده و تحت قوانین <span dir="ltr">GNU/GPL</span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span><span dir="rtl"> </span> قابل استفاده است.<br />
  ارائه پیشنهادات و  انتقادات شما به تیم برنامه نویسی گروه کارانشان باعث قوت قلب و پیشرفت در پروژه  های آتی خواهد شد.<br />
  <br>
  <strong>شاهین غرقی</strong><br  />
info@Karaneshan.com</p>
</div>
